### PR TITLE
conf: set release FEEDURIPREFIX

### PR DESCRIPTION
**Pull request by KanjiMonster**
Set the FEEDURIPREFIX to the release path.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>

### CODE REVIEW

**Comment by KanjiMonster** [comment]
Marking as draft as we should only merge this after verifying that the checksum are actually identical.

**Comment by KanjiMonster** [comment]
I verified that the ofdpa recipe pulls the packages from the right location, but obviously fails because the packages don't exist yet.

```
--2021-10-05 12:39:47--  http://repo.bisdn.de/pub/onie/accton-as4610/packages-v4.2.0/ipk/accton_as4610/ofdpa_3.0.5.0-EA5+sdk-6.5.22+git0+ce97ed9907_f01ceb9cf4-r4_accton_as4610.ipk
Resolving repo.bisdn.de (repo.bisdn.de)... 52.219.171.60
Connecting to repo.bisdn.de (repo.bisdn.de)|52.219.171.60|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-10-05 12:39:48 ERROR 404: Not Found.
```

**Review by rubensfig — COMMENTED** [review]
Cant this be added to the local.conf by default?

**Comment by KanjiMonster** [comment]
No, since for master we want them to pull the nightly packages, not the release packages

**Review by rubensfig — APPROVED** [review]

**Pull request merged**
