### PR TITLE
conf: set release FEEDURIPREFIX

### PR DESCRIPTION
**Pull request by jklare**
Set the FEEDURIPREFIX to the release path.

Signed-off-by: hilmar.magnusson <hilmar.magnusson@bisdn.de>

### CODE REVIEW

**Review by KanjiMonster — CHANGES_REQUESTED** [review]
The author and the Signed-off-by should match. Please choose one:

a) a commit by me, signed off by me
b) a commit by you, signed off by you

**Comment by jklare** [comment]
> The author and the Signed-off-by should match. Please choose one:
> 
> a) a commit by me, signed off by me b) a commit by you, signed off by you

I did not create this commit, i just cherry picked it. So i think keeping the original commit, including the sign-off is correct here. Option b) will not work at all for the DCO bot.

**Comment by KanjiMonster** [comment]
> > 
> 
> I did not create this commit, i just cherry picked it. So i think keeping the original commit, including the sign-off is correct here. Option b) will not work at all for the DCO bot.

Then please cherry-pick one that isn't broken, e.g. https://github.com/bisdn/bisdn-linux/commit/19d9c21ae95367aa30a579f720e292ada1b120d1

**Comment by jklare** [comment]
done

**Review by KanjiMonster — APPROVED** [review]

**Pull request merged**
